version: "3.8"

services:

  mysqldb:
    image: mysql:5.7
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=achat_db
    ports:
      - 3307:3306
    volumes:
      - db:/var/lib/mysql

  achat-backend:
    depends_on:
      - mysqldb
    image: ahmedsmiai/achat
    restart: on-failure
    ports:
      - 8089:8089
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url"  : "jdbc:mysql://mysqldb:3306/achat_db?useSSL=false",
        "spring.datasource.username" : "root",
        "spring.datasource.password" : "123456",
        "spring.jpa.show-sql" : "true",
        "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQL5InnoDBDialect",
        "spring.jpa.hibernate.ddl-auto" : "update"
      }'
  achat-frontend:
    image: front1
    restart: on-failure
    ports:
      - 4200:80
    environment:
      API_BASE_URL: http://192.168.33.10:8089
volumes:
  db: