version: '3'

services:
  achat-app:
    image: nidhal2/achat:1-0
    ports:
      - "8089:8089"
    depends_on:
      - mysql-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://localhost:3306/achatdb?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=
    networks:
      - mynetwork


  mysql-db:
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_DATABASE=achatdb
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - mynetwork


networks:
  mynetwork:
    driver: bridge


volumes:
  mysql-data:
