version: '3'

services:

  db:

    image: mysql

    command: --default-authentication-plugin=mysql_native_password

    restart: always

    environment:

      MYSQL_ROOT_PASSWORD: rootpassword

    ports:

      - "3306:3306"

    expose:

      - "3306"

    volumes:

      - my-db:/var/lib/mysql


  adminer:

    image: adminer

    restart: always

    ports:

      - "9000:9090"


  spring-app:

    image: nidhal2/dev-image

    container_name: achat

    ports:

      - "8081:8081"

    depends_on:

      - db


volumes:

  my-db: